spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reji
    username: root
    password: shiyunhao123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    generator:
      write-numbers-as-strings: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
reji:
  file-sava-path: C:\WorkSpaces\data\
